services:
  springboot:
    build: .
    image: pt
    container_name: pt
    ports:
      - "8080:8080"
#    depends_on:
#      mysql:
#        condition: service_healthy
#
#  mysql:
#    image: mysql
#    container_name: community_mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
#      MYSQL_DATABASE: pt
#      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
#    ports:
#      - "3306:3306"
#    healthcheck:
#      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
#      interval: 10s
#      timeout: 5s
#      retries: 5
